export default interface Comment {
  total_awards_received: number
  approved_at_utc: any
  comment_type: any
  awarders: any[]
  mod_reason_by: any
  banned_by: any
  author_flair_type: 'text'
  removal_reason: any
  link_id: string
  author_flair_template_id: any
  likes: any
  replies: any[]
  user_reports: any[]
  saved: boolean
  id: string
  banned_at_utc: any
  mod_reason_title: any
  gilded: number
  archived: boolean
  no_follow: boolean
  author: string
  num_comments: number
  edited: boolean
  can_mod_post: boolean
  created_utc: number
  send_replies: boolean
  parent_id: string
  score: number
  author_fullname: string
  over_18: boolean
  treatment_tags: any[]
  approved_by: any
  mod_note: any
  all_awardings: any[]
  subreddit_id: string
  body: string
  link_title: string
  author_flair_css_class: any
  name: string
  author_patreon_flair: boolean
  downs: number
  author_flair_richtext: any[]
  is_submitter: boolean
  body_html: string
  gildings: any
  collapsed_reason: any
  distinguished: any
  associated_award: any
  stickied: boolean
  author_premium: boolean
  can_gild: boolean
  top_awarded_type: any
  author_flair_text_color: any
  score_hidden: boolean
  permalink: string
  num_reports: any
  link_permalink: string
  report_reasons: any
  link_author: string
  subreddit: string
  author_flair_text: any
  link_url: string
  created: number
  collapsed: boolean
  subreddit_name_prefixed: string
  controversiality: number
  locked: boolean
  author_flair_background_color: any
  collapsed_because_crowd_control: any
  mod_reports: []
  quarantine: boolean
  subreddit_type: 'public' | 'private'
  ups: number
}
